### ISSUE TITLE
Issue starting karma

### ISSUE THREAD

**Issue by rsumilang** [gunnarlium/babel-jspm-karma-jasmine-istanbul#11]
Hello - I tried running your application but I got the following error:

```
karma start karma.conf.js

/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/node_modules/glob/sync.js:321
        throw er
              ^
Error: EMFILE, too many open files '/private/tmp/babel-jspm-karma-jasmine-istanbul/src'
    at Object.fs.readdirSync (fs.js:654:18)
    at GlobSync._readdir (/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/node_modules/glob/sync.js:275:41)
    at GlobSync._processReaddir (/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/node_modules/glob/sync.js:135:22)
    at GlobSync._process (/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/node_modules/glob/sync.js:130:10)
    at new GlobSync (/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/node_modules/glob/sync.js:46:10)
    at new Glob (/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/node_modules/glob/glob.js:111:12)
    at Promise.all.cancellable.then.self.buckets (/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/lib/file-list.js:161:14)
    at Array.map (native)
    at List._refresh (/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/lib/file-list.js:153:37)
    at List.refresh (/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/lib/file-list.js:252:27)
    at Server._start (/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/lib/server.js:177:12)
    at invoke (/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.start (/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/lib/server.js:101:18)
    at Object.exports.run (/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/lib/cli.js:231:26)
    at Object.<anonymous> (/private/tmp/babel-jspm-karma-jasmine-istanbul/node_modules/karma/bin/karma:3:23)
```

A little google search and I found the following suggestion (https://github.com/Workiva/karma-jspm/issues/97) to modify my `/etc/security/limits.conf`. This didn't seem like a good idea and I was wondering if you had another solution.

I'm on Mac OS X 10.11.

Thanks!

**Comment by gunnarlium** [comment]
What version of Node are you using? I'm on a Mac myself, and haven't seen this. I just ran through everything using the latest v4 and v5 of Node, with no issues.

**Comment by rsumilang** [comment]
Ah. I was on v0.10.28. Upgraded now to v4.2.3 and deleted my ~/.npm directory. Now everything works fine thanks!

Unrelated: Bonus points to see an example of karma-coverage working with browserify + babel. ;)

**Comment by gunnarlium** [comment]
I haven't used Browserify extensively, but I think the code coverage parts will be the same, so if you just get karma wokring with Browserify, the rest should (hopefully) just work.

**Comment by rsumilang** [comment]
Yeah that's what I thought too. The reports get generated but the progress/percent says 100% on all files even if there is only coverage for 1 method of a class.

Sorry I know this is getting way off topic for your project. Please let me know if you are willing to discuss offline. Thanks again!
